<?php


/* check if user has rights to manage options. */
if (!current_user_can('manage_options') && !current_user_can('manage_options_oes')) :
    ?>
    <div class="notice notice-error">
        <p><?php _e('Sorry, you are not allowed to manage options for this site.', 'oes'); ?></p>
    </div>
    <?php
    wp_die();
endif;
settings_errors();


?>
<div class="oes-settings-form-wrapper" id="settings-page">
    <!-- dummy for admin notices -->
    <h2 class="dummy-admin-notices"></h2>
    <h2 id="oes-settings"><?php _e('Theme Information', 'oes-demo'); ?></h2>
    <p><?php
        _e("This is a settings page generated by the OES Demo Plugin. You could add your own project
        configuration concerning this plugin here. For the OES Demo Project this is only a page giving you
        configuration settings and basic information about the OES Demo Theme.", 'oes-demo');?>
    </p>
    <?php

    /* display warning if oes theme is not active */
    $themeActive = ' ';
    if (!in_array(wp_get_theme()->name, ['oes', 'OES'])):
        $themeActive = ' style="display:none"';
        ?>
        <div class="notice notice-warning is-dismissible">
        <p><?php _e('OES Demo theme (oes) is not installed. To access the demo pages, 
            please install the OES demo theme.', 'oes-demo'); ?></p>
        </div><?php
    endif;
    ?>
    <p><?php _e('If you are using the OES Demo Theme or a WordPress Theme based on the OES Demo Theme you can 
configure and administrate theme settings that will be visible on your website (frontend).', 'oes'); ?></p>
    <h2 id="oes-settings" <?php echo $themeActive; ?>><?php
        _e('How to get to the landing page', 'oes-demo'); ?></h2>
    <p><?php
        printf(__('After installing the OES Core Plugin, the OES Demo Plugin and the OES Demo Theme you can access the 
        demo pages %s by clicking on the image below. On the demo page you can experience the frontend of an exemplary 
        application based on the OES Demo Plugin.', 'oes-demo'),
            '<a href="' . site_url() . '" target="_blank">' . site_url() . '</a>');?>
    </p>
    <div<?php echo $themeActive; ?>>
        <a href="<?php echo site_url() ?>" target="_blank">
            <img src="<?php echo plugins_url('/oes-demo/assets/images/Demo_Home_Page.png'); ?>"
                 id="frontend-link"
                 alt="demoPage">
        </a>
    </div>
</div>